prefix dc:      <http://purl.org/dc/elements/1.1/> 
prefix owl:     <http://www.w3.org/2002/07/owl#> 
prefix qudt:    <http://qudt.org/schema/qudt#> 
prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> 
prefix skos:    <http://www.w3.org/2004/02/skos/core#> 
prefix xsd:     <http://www.w3.org/2001/XMLSchema#> 
prefix bbp:     <http://bluebrain.epfl.ch/ontology/units/> 


SELECT ?s ?type ?label ?abbrev ?convMult ?convOffset ?symbol
{
?s rdf:type ?type .
?s rdfs:label ?label .
OPTIONAL { ?s qudt:abbreviation ?abbrev } .
OPTIONAL { ?s qudt:symbol ?symbol } .
OPTIONAL { ?s qudt:conversionMultiplier ?convMult } .
OPTIONAL { ?s qudt:conversionOffset ?convOffset } 
}